#! /bin/bash

# Embed client
cp docs/embed/.javascript.md docs/embed/javascript.md
curl https://raw.githubusercontent.com/FlatIO/embed-client/master/README.md | tail -n +5 >> docs/embed/javascript.md
